apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-network
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-network
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration provides a foundation to build and operate AWS networks.
    meta.crossplane.io/readme: |
     This configuration is used for deploying and managing AWS network clusters on Kubernetes using Crossplane. This setup provides the necessary infrastructure to deploy AWS network managed with Crossplane in Kubernetes. This approach ensures a flexible, streamlined deployment workflow.

     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-aws-network).
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v1.4.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.5.0"
