apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.aws.platform.upbound.io
  labels:
    provider: aws
    type: basic
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: providerConfigRef
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
          - name: deletionPolicy
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
          - name: network-id
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.labels[networks.aws.platform.upbound.io/network-id]
          - name: network-id-tags
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: spec.forProvider.tags[networks.aws.platform.upbound.io/network-id]
          - name: region
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region
        resources:
          - name: vpc
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: VPC
              spec:
                forProvider:
                  cidrBlock: 192.168.0.0/16
                  enableDnsHostnames: true
                  enableDnsSupport: true
                  tags:
                    Name: ""
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.tags["Name"]
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.vpcId

          - name: internetGateway
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: InternetGateway
              spec:
                forProvider:
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region

          - name: subnetPublicA
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: public
              spec:
                forProvider:
                  cidrBlock: 192.168.0.0/18
                  mapPublicIpOnLaunch: true
                  tags:
                    kubernetes.io/role/elb: "1"
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: network-id-tags
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.availabilityZone
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: metadata.labels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.subnetIds[0]
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.publicSubnetIds[0]

          - name: subnetPublicB
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: public
              spec:
                forProvider:
                  cidrBlock: 192.168.64.0/18
                  mapPublicIpOnLaunch: true
                  tags:
                    kubernetes.io/role/elb: "1"
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: network-id-tags
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.availabilityZone
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: metadata.labels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.subnetIds[1]
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.publicSubnetIds[1]

          - name: subnetPrivateA
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: private
              spec:
                forProvider:
                  cidrBlock: 192.168.128.0/18
                  tags:
                    kubernetes.io/role/internal-elb: "1"
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.availabilityZone
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: metadata.labels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.subnetIds[2]
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.privateSubnetIds[0]

          - name: subnetPrivateB
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: Subnet
              metadata:
                labels:
                  access: private
              spec:
                forProvider:
                  cidrBlock: 192.168.192.0/18
                  tags:
                    kubernetes.io/role/internal-elb: "1"
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.availabilityZone
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: metadata.labels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.subnetIds[3]
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.privateSubnetIds[1]

          - name: routeTable
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: RouteTable
              spec:
                forProvider:
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region

          - name: route
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: Route
              spec:
                forProvider:
                  destinationCidrBlock: 0.0.0.0/0
                  gatewayIdSelector:
                    matchControllerRef: true
                  routeTableIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region

          - name: mainRouteTableAssociation
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: MainRouteTableAssociation
              spec:
                forProvider:
                  routeTableIdSelector:
                    matchControllerRef: true
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region

          - name: routeTableAssociationPublicA
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: RouteTableAssociation
              spec:
                forProvider:
                  routeTableIdSelector:
                    matchControllerRef: true
                  subnetIdSelector:
                    matchControllerRef: true
                    matchLabels:
                      access: public
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format

          - name: routeTableAssociationPublicB
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: RouteTableAssociation
              spec:
                forProvider:
                  routeTableIdSelector:
                    matchControllerRef: true
                  subnetIdSelector:
                    matchControllerRef: true
                    matchLabels:
                      access: public
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format

          - name: routeTableAssociationPrivateA
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: RouteTableAssociation
              spec:
                forProvider:
                  routeTableIdSelector:
                    matchControllerRef: true
                  subnetIdSelector:
                    matchControllerRef: true
                    matchLabels:
                      access: private
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sa'
                      type: Format

          - name: routeTableAssociationPrivateB
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: RouteTableAssociation
              spec:
                forProvider:
                  routeTableIdSelector:
                    matchControllerRef: true
                  subnetIdSelector:
                    matchControllerRef: true
                    matchLabels:
                      access: private
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[zone]
                transforms:
                  - type: string
                    string:
                      fmt: '%sb'
                      type: Format

          - name: securityGroup
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroup
              spec:
                forProvider:
                  description: Allow access to databases
                  name: platform-ref-aws-cluster
                  vpcIdSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.securityGroupIds[0]

          - name: securityGroupRulePostgres
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroupRule
              spec:
                forProvider:
                  cidrBlocks:
                    - 0.0.0.0/0
                  description: Everywhere
                  fromPort: 5432
                  protocol: tcp
                  securityGroupIdSelector:
                    matchControllerRef: true
                  toPort: 5432
                  type: ingress
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region

          - name: securityGroupRuleMysql
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroupRule
              spec:
                forProvider:
                  cidrBlocks:
                    - 0.0.0.0/0
                  description: Everywhere
                  fromPort: 3306
                  protocol: tcp
                  securityGroupIdSelector:
                    matchControllerRef: true
                  toPort: 3306
                  type: ingress
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: network-id
              - type: PatchSet
                patchSetName: region
