name: render-test
on:
 - pull_request
 - push
jobs:
  test:
    name: runner / render-test
    runs-on: e2-standard-8
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run KCL Unit-Tests
        id: run-kcl-test
        run: |
          set -eo pipefail
          make submodules
          make render.test
